# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mondrian/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mondrian)

$(call add-radio-file-sha1-checked,radio/abl.img,70ec56ba5cb0b28f05288e2da0f3f75773031ed7)
$(call add-radio-file-sha1-checked,radio/aop.img,bced9bf9220559e3115f24f4986d61dcca39674e)
$(call add-radio-file-sha1-checked,radio/aop_config.img,11dda684e7e0432a9b43be5f5462490d01ed86d6)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,1ea43b5dd96b37457e189f79a1086d3898a1fda7)
$(call add-radio-file-sha1-checked,radio/cpucp.img,a5e68bd0c16fd6f061156237c8770034adf54062)
$(call add-radio-file-sha1-checked,radio/devcfg.img,e913a343839b9ed7543efbb96fd29db5ab2c00e2)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,28c289e7d8fe9cc072aeae76771afef0c8f71fbf)
$(call add-radio-file-sha1-checked,radio/hyp.img,886c6c2049a12524061b48afc96ed8ffaa6ed432)
$(call add-radio-file-sha1-checked,radio/imagefv.img,dbbe559ef0b8e4f9cc21174b3a2b325e603041ff)
$(call add-radio-file-sha1-checked,radio/keymaster.img,7279581af62ee24617be73ded05cf80e742a3962)
$(call add-radio-file-sha1-checked,radio/modem.img,ce3d4ce609d0484f2d37116dff766aee7836a779)
$(call add-radio-file-sha1-checked,radio/qupfw.img,c27b6fb213e64ea7eee57613df67f42d0f57da76)
$(call add-radio-file-sha1-checked,radio/shrm.img,a771c9edc487732937c36da411c6704f577273ae)
$(call add-radio-file-sha1-checked,radio/tz.img,fe03d23e847b60658b15d9764ed1bfe325e9e7d3)
$(call add-radio-file-sha1-checked,radio/uefi.img,04c9fb426c391009bab9e02a0e6b3aaf2843b7fa)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,333d897b82660527a599f852d9cd75d4ee0b70be)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,af74b5698036238681e745915f05ba05794fed97)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,af1531490fc0ed19065a986e3a9115c3afde409b)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,ea3f3a9b11bdd28cdc03b2e6b469a50a432d6409)

endif
